### ISSUE TITLE
iOS - White screen before splash screen 

### ISSUE THREAD

**Issue by Aljulanda9** [henriquearthur/flutter_native_splash#9] opened 2019-08-28 22:06 UTC
Hi, thanks for the wonderful package. It saved me a lot of time. I have a small issue with the iOS splash screen. It works fine, but there's a white screen right before the splash screen that I specified. Have you seen this before or would you know of a way to get rid of that initial white screen? Thanks
- Edit: device is iPhone 6

**Comment by henriquearthur** [comment] 2019-08-28 23:42
I can not reproduce this on iOS emulator and unfortunately I don't have a Mac or real device to test this on.

Can you provide more information like:
- Are you using Objective-C or Swift?
- Does this happens only on the iPhone 6 or emulator as well?
- Please share your `ios/Runner/Base.lproj/LaunchScreen.storyboard`

**Comment by joaowd** [comment] 2019-09-04 10:51
Hello @henriquearthur 

I'm having the same problem, this happens on physical device but also on the emulator.

You can see a video what really happens: [YouTube](https://youtu.be/JHTGZz2WoKo)

(Also I don't think that black screen in the end is normal?)

File of my launchScreen.storyboard: [Storyboard](https://gist.github.com/joaowd/381aedc888c9c78666d66041c5b6ac27
)

**Comment by henriquearthur** [comment] 2019-09-05 01:51
@joaowd thank you for sharing the video, it is really helpful.

I will look into this soon.

**Comment by pph7** [comment] 2019-09-05 13:48
Hi, @henriquearthur first I want to say thank you for the great plugin, I was exactly looking for something like this. 
The only issue is, I have the same problem like @joaowd. There is a blank white screen showing before the actual splash screen.
The interesting thing is, that I had the same effect when I created my splash screen manually by modifiying the LaunchScreen.storyboard provided by flutter. I am struggling with this the whole day now.

**Comment by pph7** [comment] 2019-09-05 13:50
BTW I am working with XCode 10.3 and so far I have seen this issue on the simulator, I did not test it on a real device yet. Here is my LaunchScreen.storyboard

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="12121" systemVersion="16G29" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="12089"/>
    </dependencies>
    <scenes>
        <!--View Controller-->
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="Ydg-fD-yQy"/>
                        <viewControllerLayoutGuide type="bottom" id="xbc-2k-c8Z"/>
                    </layoutGuides>
                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" image="LaunchImage" translatesAutoresizingMaskIntoConstraints="NO" id="YRO-k0-Ey4">
                            </imageView>
                        </subviews>
                        <color key="backgroundColor" red="0.25882352941176473" green="0.6470588235294118" blue="0.9607843137254902" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
                        <constraints>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="1a2-6s-vTC"/>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="4X2-HB-R7a"/>
                        </constraints>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="53" y="375"/>
        </scene>
    </scenes>
    <resources>
        <image name="LaunchImage" width="1125" height="2436"/>
    </resources>
</document>
```

**Comment by joaowd** [comment] 2019-09-05 13:59
@pph7 and @Aljulanda9 Can you guys please test if your app hides the status bar on landscape when you use this package?

Since I installed this the status bar doesn't disappear on landscape.

**Comment by pph7** [comment] 2019-09-05 14:15
@joaowd sorry I can't reproduce this because my app does not run in landscape mode. Maybe open another issue?

**Comment by joaowd** [comment] 2019-09-05 14:17
@pph7 I would but I don't really know if the problem is related.

**Comment by henriquearthur** [comment] 2019-09-05 23:35
@Aljulanda9 @joaowd @pph7 I have tried to reproduce this issue on a iPhone XR and iPhone 6 simulator but had no success. 

I tried to create a fresh project with `flutter create`, setting up the package and running it. No white screen. I also tried running a personal project - which has more complex loading with Firebase and BLoC, but still no white screen.

Can't reproduce this on default counter example and not in a more complex app.

As you can see on the gif, there is no white or black screen.

**Can you guys check if this issue occurs with a fresh flutter project (counter example)?**

Maybe the reason I can't reproduce is because my apps are too simple, although I don't think that is a problem given the way that Flutter works, but still I would like to investigate all possibilities. Or maybe is because I'm testing on an emulator inside a Mac OS VM, but if anything that should be a _limitation_.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5016325/64389670-ff730a80-d019-11e9-8b38-56c2c0687319.gif)

**Comment by henriquearthur** [comment] 2019-09-05 23:39
@joaowd 
> Can you guys please test if your app hides the status bar on landscape when you use this package?
> 
> Since I installed this the status bar doesn't disappear on landscape.

- Have you modified `UIViewControllerBasedStatusBarAppearance` on `Info.plist`? (default is `false`)
- Does it work on portrait?

Please open a new issue so we can keep discussions separated.

**Comment by pph7** [comment] 2019-09-06 10:08
@henriquearthur I created a new flutter app and with your plugin, the image shows from the beginning. I noticed though now that when I change the background color in the settings of flutter_native_splash the color shows from the beginning, jus the image is delayed. I will investigate further.

**Comment by pph7** [comment] 2019-09-06 11:15
I was able to solve this issue for me. It turns out to be a caching issue with Flutter and XCode. After I did

`flutter clean`

and resetted the simulated iOS device, the screen showed without a delay.

**Comment by joaowd** [comment] 2019-09-06 11:20
@pph7 `flutter clean`, didn't solve my problem

**Comment by pph7** [comment] 2019-09-06 11:27
@joaowd did you also reset the simulator?

**Comment by joaowd** [comment] 2019-09-06 11:29
@pph7 What do you mean ? Quit and Open the simulator again ?

This also happens on physical devices

**Comment by pph7** [comment] 2019-09-06 11:30
Erase all Content and Settings https://stackoverflow.com/a/9088416/284577

**Comment by joaowd** [comment] 2019-09-06 11:40
@pph7 That actually worked! But how we do fix this on a real device ?

**Comment by joaowd** [comment] 2019-09-06 11:59
Alright for some weird reason, It started working well on a real device.

**Comment by pph7** [comment] 2019-09-06 12:37
@joaowd Great! Caching issues related to the launch screen seem to be very common, as I read in a couple of stackoverflow questions, many of them unrelated to flutter.

**Comment by henriquearthur** [comment] 2019-09-06 21:05
As @pph7 pointed out this seems to be a caching problem in iOS development (not related to Flutter or flutter_native_splash) and also a frequent issue:

- https://forums.developer.apple.com/thread/105790
- https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update

---
Explaining to future readers: `flutter clean` will delete your build so you have to build again from original code and resetting iOS simulator will clear out the cache.

I will add this information to README on next version so people can solve this quickly.

@Aljulanda9 please try this steps on your app and let us know if it works for you too. I am closing this issue because the solution works for other people with same problem - but if it doesn't work for you then please reopen so we can dig deeper.

And thanks @pph7 for the solution!

**Closed by henriquearthur** 2019-09-06 21:05 UTC
Labels: bug, ios

**Comment by Aljulanda9** [comment] 2019-09-07 06:42
Hi yes the trick worked. Thank you very much :)

**Comment by pph7** [comment] 2019-09-07 10:48
Happy to help

**Comment by softronaut** [comment] 2019-11-28 12:10
I have same issue and even `flutter clean` is not working. Also the delay is a little longer than the gif up above. There is video from mtechviral and he says that delay related the wrong spec image. But it's just a simple png what could be wrong?

**Comment by pph7** [comment] 2019-11-28 12:28
@softronaut did you also try to reset the simulator?

**Comment by softronaut** [comment] 2019-11-28 12:37
@pph7 yes, right now I tried with different device, same issue. Actually I realised this issue after `ipa` build. I think this is iOS issue at general.

**Comment by pph7** [comment] 2019-11-28 13:40
@softronaut right, an iOS issue and a caching issue in particular

**Comment by softronaut** [comment] 2019-11-28 17:24
I can confirm it's related the image file and caching. I'm not expert at images but I was using a file exported from Photoshop. Now I used a generator and I think it changes the files structure, now it's loading instantly.

**Comment by esskar** [comment] 2020-06-24 10:23
@softronaut what image sizes are you using?

**Comment by softronaut** [comment] 2020-06-24 10:49
> @softronaut what image sizes are you using?

It was not related to size as far as I remember. Just try to optimize image via some web services or save again in something like GIMP, Krita etc. then try again. That's how I managed to solve it.

**Comment by robvr** [comment] 2020-07-02 09:33
@softronaut How did you manage to solve this issue? I mean what optimization did you apply to the image using GIMP or Krita? I tried the flutter clean method and nothing is being solved

**Comment by softronaut** [comment] 2020-07-02 09:56
> @softronaut How did you manage to solve this issue? I mean what optimization did you apply to the image using GIMP or Krita? I tried the flutter clean method and nothing is being solved

There are web services for image size optimization, you can try them. As far as I remember I didn't do any optimization in my case, just did `Save as`(may be GIMP or may be Preview tool from Mac I can't remember exactly) and it worked.

The point is here, when you save or export image from any other software, it changes the image internally according it's algorithm and that's somehow solves the problem sometimes.

**Comment by yourshinsuke** [comment] 2020-09-08 03:09
did you fix?

**Comment by pph7** [comment] 2020-09-08 07:43
@yourshinsuke please check my reply, it is most likely a caching issue

**Comment by wlgnsdi** [comment] 2022-01-04 07:47
> Erase all Content and Settings https://stackoverflow.com/a/9088416/284577

Thanks!! this is my answer!! :)
